sudo: required
language: cpp
services:
  - docker
env:
  # Configurations
  matrix:
    # Build and test everything but use Clang as the compiler x86_64
    - LINUX_BASE=ubuntu_14.04 C_COMPILER=/usr/bin/clang-3.9 CXX_COMPILER=/usr/bin/clang++-3.9 TARGET_ARCH=x86_64
    # Build and test everything but use GCC as the compiler x86_64
    - LINUX_BASE=ubuntu_14.04 C_COMPILER=/usr/bin/gcc CXX_COMPILER=/usr/bin/g++ TARGET_ARCH=x86_64
    # Build and test everything but use GCC as the compiler x86_64
    - LINUX_BASE=ubuntu_14.04 C_COMPILER=/usr/bin/gcc CXX_COMPILER=/usr/bin/g++ TARGET_ARCH=i686
    # Build and test everything but use Clang as the compiler i686
    - LINUX_BASE=ubuntu_14.04 C_COMPILER=/usr/bin/clang-3.9 CXX_COMPILER=/usr/bin/clang++-3.9 TARGET_ARCH=i686

# TODO: OSX support
#matrix:
#  include:
#    - os: osx
#      osx_image: xcode 8.2
script:
  - contrib/ci/scripts/travis_ci_entry_point.sh
